basePath: /
host: ws-nilai.herokuapp.com
info:
  contact:
    email: 1214039@std.ulbi.ac.id
    name: API Support
    url: https://github.com/Febriand1
  description: This is a sample server.
  title: TES  SWAG
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
