basePath: /
definitions:
  controller.Dosen:
    properties:
      namadosen:
        description: ID            primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"`
        example: Rizkyria
        type: string
      nik:
        example: 123.456.789
        type: string
      phonenumberd:
        example: "089876543210"
        type: string
    type: object
  controller.Grade:
    properties:
      namagrade:
        example: A
        type: string
      skala:
        example: "75.87"
        type: string
    type: object
  controller.Mahasiswa:
    properties:
      nama:
        description: ID           primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"123456789" `
        example: Tes Swagger
        type: string
      npm:
        example: 1234567
        type: integer
      phonenumber:
        example: "08123456789"
        type: string
    type: object
  controller.Matakuliah:
    properties:
      jadwal:
        $ref: '#/definitions/controller.Waktu'
      nama_mk:
        description: ID       primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"
          example:"123456789"`
        example: Pemrograman III
        type: string
      pengampu:
        $ref: '#/definitions/controller.Dosen'
      sks:
        example: 1
        type: integer
    type: object
  controller.Nilai:
    properties:
      absensi:
        $ref: '#/definitions/controller.Presensi'
      alltugas:
        allOf:
        - $ref: '#/definitions/controller.Tugas'
        description: ID        primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"`
      grade:
        $ref: '#/definitions/controller.Grade'
      kategori:
        $ref: '#/definitions/controller.Matakuliah'
      uas:
        example: 123
        type: integer
      uts:
        example: 123
        type: integer
    type: object
  controller.Presensi:
    properties:
      biodata:
        $ref: '#/definitions/controller.Mahasiswa'
      jumlahkehadiran:
        description: ID               primitive.ObjectID `bson:"_id,omitempty" json:"_id,omitempty"`
        example: 1
        type: integer
    type: object
  controller.Tugas:
    properties:
      tugas1:
        example: 123
        type: integer
      tugas2:
        example: 123
        type: integer
      tugas3:
        example: 123
        type: integer
      tugas4:
        example: 123
        type: integer
      tugas5:
        example: 123
        type: integer
    type: object
  controller.Waktu:
    properties:
      hari:
        example:
        - Senin
        - Selasa
        - Rabu
        - Kamis
        - Jumat
        - Sabtu
        - Minggu
        items:
          type: string
        type: array
      jamkeluar:
        example: "16:00"
        type: string
      jammasuk:
        example: "08:00"
        type: string
    type: object
host: ws-nilai.herokuapp.com
info:
  contact:
    email: 1214039@std.ulbi.ac.id
    name: API Support
    url: https://github.com/Febriand1
  description: This is a sample server.
  title: TES  SWAG
  version: "1.0"
paths:
  /delete/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data presensi.
      tags:
      - Presensi
  /delnilai/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data nilai.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data nilai.
      tags:
      - Nilai
  /ins:
    post:
      consumes:
      - application/json
      description: Input data presensi.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data presensi.
      tags:
      - Presensi
  /insnilai:
    post:
      consumes:
      - application/json
      description: Input data nilai.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Nilai'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Nilai'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data nilai.
      tags:
      - Nilai
  /nilai:
    get:
      consumes:
      - application/json
      description: Mengambil semua data nilai.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Nilai'
      summary: Get All Data Nilai.
      tags:
      - Nilai
  /nilai/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data nilai.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Nilai'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Nilai.
      tags:
      - Nilai
  /presensinew:
    get:
      consumes:
      - application/json
      description: Mengambil semua data presensi.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
      summary: Get All Data Presensi.
      tags:
      - Presensi
  /presensinew/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Presensi.
      tags:
      - Presensi
  /upd/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Presensi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Presensi'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data presensi.
      tags:
      - Presensi
  /updnilai/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data nilai.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.Nilai'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Nilai'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data nilai.
      tags:
      - Nilai
schemes:
- https
- http
swagger: "2.0"
